version: '3.7'

services:



  front:
    build: ./reto
    depends_on:
      - db
    volumes:
      - ./reto:/usr/share/nginx/html
    networks:
      - JonCOnet

  generador:
    build: ./generadorDatos
    # ports:
    #   - 3000:80
    command: sh -c 'while true; do php /app/generadorDatos.php; sleep 60; done'
    volumes:
      - ./generadorDatos:/app
    depends_on:
      - db
    networks:
      - JonCOnet

  laravel1:
    build: ./retolaravel
    # command: php artisan migrate:fresh --seed
    image: laravel.prod
    # volumes:
    #   - ./api:/src/app
    # ports:
    #   - 8000:80
    depends_on:
      - db
    networks:
      - JonCOnet

  laravel2:
    build: ./retolaravel
    # command: php artisan migrate:fresh --seed
    image: laravel.prod
    # volumes:
    #   - ./api:/src/app
    # ports:
    #   - 8000:80
    depends_on:
      - db
    networks:
      - JonCOnet
  db:
    image: mysql
    command: --max_allowed_packet=325058560
    environment: 
      MYSQL_ROOT_PASSWORD: reto
      MYSQL_USER: reto
      MYSQL_DATABASE: reto
      MYSQL_PASSWORD: reto
    volumes: 
      - ./dump:/docker-entrypoint-initdb.d
      - /mysql:/var/lib/mysql

    networks:
      - JonCOnet
    ports:
      - 3306:3306


  phpmyadmin:
          depends_on:
              - db
          image: 'phpmyadmin/phpmyadmin:latest'
          restart: always
          environment:
              PMA_HOST: db
              PMA_PORT: 3306
              PMA_USER: 'reto'
              PMA_PASSWORD: 'reto'
          networks:
              - JonCOnet
          ports:
              - 83:80
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - JonCOnet
    depends_on:
      - laravel1
      - laravel2
networks:
    JonCOnet:
        driver: bridge
  # volumes:
  #     sail-mysql:
  #         driver: local